version: "3.7"

services:
  webapp:
    build: 
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./quotegame:/code
    ports:
      - "8005:8000"
      - "6379:6397"
    environment:
      - DJANGO_REDIS_HOST=redis
      - DJANGO_REDIS_PORT=6379
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis
  
  