# Generated by Django 3.2.5 on 2022-07-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='person',
            field=models.CharField(default='Daniel Reynolds', max_length=100),
            preserve_default=False,
        ),
    ]
