# Generated by Django 3.2.5 on 2022-07-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quote_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='timestamp',
            field=models.IntegerField(default=0),
        ),
    ]
